### PR TITLE
chore: update port from 5000 to 5001 for server

### PR DESCRIPTION
**Pull request by artemrys**
Updating port from 5000 to 5001 for `server` to unblock folks who run on a newer macOS version.

### CODE REVIEW

**Comment by artemrys** [comment]
@vtsvetkov-splunk can you please try to run this branch in your environment and see if this PR fixes it for you?

**Comment by hetangmodi-crest** [comment]
Perhaps, can [this solution](https://stackoverflow.com/a/72369347) be tried instead? Changing the port doesn't concern us either way.

**Review by vtsvetkov-splunk — APPROVED** [review]
It works, but I don't see the reason to expose this port to the host machine. We can safely remove `ports` from docker compose and `EXPOSE` from Dockerfile

It will be still accessible by the splunk container

**Comment by vtsvetkov-splunk** [comment]
Potentially may be superseded by #14

**Pull request closed without merging**
